name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Skia
        shell: bash
        run: |
          this_dir="${{ github.workspace }}"
          skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
          skia_file=$(basename "$skia_url")
          curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
          unzip "$skia_file" -d skia

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: macos-release

      - uses: aseprite/get-ninja@main

      - name: Generating Makefiles
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DENABLE_TESTS=ON \
            -DENABLE_SCRIPTING=ON \
            -DENABLE_CCACHE=ON \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-arm64)

      - name: Compile
        shell: bash
        run: |
          cd build
          ninja

      - name: Run C++ Tests
        shell: bash
        run: |
          cd build
          ctest --output-on-failure

      - name: Run CLI Tests
        shell: bash
        run: |
          export ASEPRITE=$PWD/build/bin/aseprite
          cd tests
          bash run-tests.sh

      - name: Show build files
        shell: bash
        run: |
          echo "===== BUILD FILES ====="
          find build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-macos
          path: build/bin
